---
version: "2.0"

services:
  app:
    image: dimokus88/ubuntu:1.1
    env:
#1.Раздел часной информации, неделитесь даннмы из этого раздела!
#1.Private information section, do not share data from this section!
      - "my_root_password=" # Root password far a ssh connection. Пароль root для подключения по ssh.
      - "MONIKER=" # Node name. Use "Akash" in moniker(for example:Dimokus_Akash) to help develop the project! Имя ноды. Используйте в моникере "Akash"(например:Dimokus_Akash) что бы помочь в развитии проекта!
      - "LINK_KEY=" # link to the posted pirv-validator_key.json (direct download). It will also work from other Cosmos-based testnets.Ссылка на размещенный pirv-validator_key.json (прямое скачивание). Подойдет и от других тестнетов на базе Cosmos.
#==================================================================
#2.Раздел переменных для работы ноды
#2.Section of variables for node operation"
      - "binary=haqqd"
      - "vers=v1.0.3"
      - "genesis=https://raw.githubusercontent.com/haqq-network/validators-contest/master/genesis.json"
      - "folder=.haqqd"
      - "denom=aISLM"
      - "chain=haqq_54211-2"
      - "gitrep=https://github.com/haqq-network/haqq.git"
      - "gitfold=haqq"
      #- "SHIFT=4000"
      - "PEER=b3ce1618585a9012c42e9a78bf4a5c1b4bad1123@65.21.170.3:33656,952b9d918037bc8f6d52756c111d0a30a456b3fe@213.239.217.52:29656,85301989752fe0ca934854aecc6379c1ccddf937@65.109.49.111:26556,d648d598c34e0e58ec759aa399fe4534021e8401@109.205.180.81:29956,f2c77f2169b753f93078de2b6b86bfa1ec4a6282@141.95.124.150:20116,eaa6d38517bbc32bdc487e894b6be9477fb9298f@78.107.234.44:45656,37513faac5f48bd043a1be122096c1ea1c973854@65.108.52.192:36656,d2764c55607aa9e8d4cee6e763d3d14e73b83168@66.94.119.47:26656,fc4311f0109d5aed5fcb8656fb6eab29c15d1cf6@65.109.53.53:26656,297bf784ea674e05d36af48e3a951de966f9aa40@65.109.34.133:36656,bc8c24e9d231faf55d4c6c8992a8b187cdd5c214@65.109.17.86:32656"
      - "SEED=62bf004201a90ce00df6f69390378c3d90f6dd7e@seed2.testedge2.haqq.network:26656,23a1176c9911eac442d6d1bf15f92eeabb3981d5@seed1.testedge2.haqq.network:26656"
      #- "SNAP_RPC=http://haqq.stake-take.com:36657"  
    command:
      - "bash"
      - "-c"
    args:
      - 'curl -s https://raw.githubusercontent.com/Dimokus88/universe/main/main.sh | bash '
    expose:
      - port: 80
        as: 80
        to:
          - global: true
      - port: 22
        as: 22
        to:
          - global: true
      - port: 26656
        as: 26656
        to:
          - global: true
      - port: 26657
        as: 26657
        to:
          - global: true
        
profiles:
  compute:
    app:
      resources:
        cpu:
          units: 4.0
        memory:
          size: 6Gi
        storage:
          size: 200Gi
        
        
  placement:
    akash: 
      pricing:
        app:
          denom: uakt
          amount: 10000
deployment:
  app:
    akash:
      profile: app
      count: 1 
